sudo: false
stages:
  - name: Unit tests

language: node_js
node_js: 10.2.1

cache:
  directories:
    - node_modules

install:
  - npm install

jobs:
  include:
    - stage: Unit tests
      script: npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox
